#!/bin/sh

symbol() {
[ $(cat /sys/class/net/w*/operstate) = down ] && echo 睊 && exit
echo 直
}

name() {
iwctl station wlan0 show | grep "Connected network" | sed 's/Connected\ network\ \ \ /Connected to /g' | cut -d ':' -f2
}

[ "$1" = "icon" ] && symbol && exit
[ "$1" = "name" ] && name && exit
