#!/bin/sh

handle () {
    if [[ ${1:0:9} == "workspace" ]]; then
        workspaces=()
        index=1
        last=$(hyprctl workspaces | grep workspace | sed 's/.*(\(.*\)).*/\1/g' | sort | tail -1)
        necessary_workspaces=$(( $last > ${1:11} ? $last : ${1:11} ))
        for workspace in $(seq 1 $necessary_workspaces)
        do
            full_screen=$(hyprctl workspaces | awk '/\('$index'\)/{getline; getline; print $2}' | grep . || echo 0)
            if (( ${1:11} == $workspace )); then
                if (( $full_screen )); then
                    workspaces+=("[$index,\"■\"]")
                else
                    workspaces+=("[$index,\"◆\"]")
                fi
            else
                if (( $full_screen )); then
                    workspaces+=("[$index,\"□\"]")
                else
                    workspaces+=("[$index,\"◇\"]")
                fi
            fi
            index=$(( $index + 1 ))
        done

        eww update workspace_list=$(echo [${workspaces[@]}] | sed 's/ /,/g')
    fi
}

handle "workspace>>1"

socat - UNIX-CONNECT:/tmp/hypr/$(echo $HYPRLAND_INSTANCE_SIGNATURE)/.socket2.sock |\
while read line
do
    handle $line
done
