# I relented.
source "%val{config}/plugins/plug.kak/rc/plug.kak"
plug "andreyorst/plug.kak" noload

set-option global tabstop 4

add-highlighter global/ wrap
add-highlighter global/ number-lines -relative

hook global WinSetOption filetype=rs %{
    add-highlighter -override window/ wrap -width=100
}

hook global ModeChange pop:insert:normal %{
    write
}

# Exit insert mode with `jk`.
hook global InsertChar k %{ try %{
    exec -draft hH <a-k>jk<ret> d
    exec <esc>
}}

# Move in autocompletion with tab
hook global InsertCompletionShow .* %{
    try %{
        # this command temporarily removes cursors preceded by whitespace;
        # if there are no cursors left, it raises an error, does not
        # continue to execute the mapping commands, and the error is eaten
        # by the `try` command so no warning appears.
        execute-keys -draft 'h<a-K>\h<ret>'
        map window insert <tab> <c-n>
        map window insert <s-tab> <c-p>
        hook -once -always window InsertCompletionHide .* %{
        unmap window insert <tab> <c-n>
        unmap window insert <s-tab> <c-p>
        }
    }
}

plug 'delapouite/kakoune-auto-percent'
plug "andreyorst/smarttab.kak"
plug "delapouite/kakoune-palette"

plug 'NNBnh/clipb.kak' config %{
    clipb-detect
    clipb-enable
}
    
plug "kak-lsp/kak-lsp" do %{
    cargo install --locked --force --path .
}
